import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f6f3ef',
  },
  screen: {
    gap: 18,
    padding: 20,
    paddingBottom: 36,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingTop: 8,
  },
  headerText: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  eyebrow: {
    color: '#6f5d51',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  title: {
    color: '#241c18',
    fontSize: 34,
    fontWeight: '800',
  },
  installButton: {
    alignItems: 'center',
    backgroundColor: '#784c61',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  installButtonDisabled: {
    backgroundColor: '#e8dfd7',
  },
  installButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  installButtonTextDisabled: {
    color: '#8a7c73',
  },
  resultPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#ded4cb',
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  resultGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  metric: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  metricLabel: {
    color: '#6f5d51',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: '#241c18',
    fontSize: 30,
    fontWeight: '800',
  },
  subtype: {
    alignSelf: 'flex-start',
    backgroundColor: '#e9f2ef',
    borderRadius: 6,
    color: '#183d35',
    fontSize: 15,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  form: {
    gap: 18,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: 12,
  },
  optionGroup: {
    gap: 8,
  },
  fieldLabel: {
    color: '#3a312d',
    fontSize: 14,
    fontWeight: '700',
  },
  segmentedControl: {
    backgroundColor: '#e8dfd7',
    borderRadius: 8,
    flexWrap: 'wrap',
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  optionButton: {
    alignItems: 'center',
    borderRadius: 6,
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  optionButtonWrapped: {
    flexBasis: 52,
  },
  optionButtonActive: {
    backgroundColor: '#784c61',
  },
  optionText: {
    color: '#4e433d',
    fontSize: 14,
    fontWeight: '700',
  },
  optionTextActive: {
    color: '#ffffff',
  },
  optionDescription: {
    color: '#6f5d51',
    fontSize: 12,
    lineHeight: 17,
  },
  selectorGroup: {
    gap: 8,
  },
  selectorGroupFill: {
    flex: 1,
    minWidth: 0,
  },
  selectorField: {
    backgroundColor: '#ffffff',
    borderColor: '#d8ccc2',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    minHeight: 92,
    padding: 12,
  },
  selectorValueRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  selectorValue: {
    color: '#241c18',
    fontSize: 24,
    fontWeight: '800',
  },
  selectorAction: {
    color: '#784c61',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  selectorDescription: {
    color: '#6f5d51',
    fontSize: 12,
    lineHeight: 17,
  },
  biomarkers: {
    flexDirection: 'row',
    gap: 12,
  },
  biomarkerToggle: {
    flex: 1,
    gap: 8,
  },
  oncotypeGroup: {
    gap: 8,
  },
  oncotypeInputRow: {
    flexDirection: 'row',
    gap: 10,
  },
  oncotypeInput: {
    backgroundColor: '#ffffff',
    borderColor: '#d8ccc2',
    borderRadius: 8,
    borderWidth: 1,
    color: '#241c18',
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  clearButton: {
    alignItems: 'center',
    backgroundColor: '#e8dfd7',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  clearButtonText: {
    color: '#4e433d',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  notesPanel: {
    backgroundColor: '#fff8df',
    borderColor: '#e2ca83',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  notesTitle: {
    color: '#3c2c11',
    fontSize: 16,
    fontWeight: '800',
  },
  note: {
    color: '#4b3b20',
    fontSize: 14,
    lineHeight: 20,
  },
  installPromptBackdrop: {
    backgroundColor: 'rgba(36, 28, 24, 0.36)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  installPromptCard: {
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#ded4cb',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    maxWidth: 420,
    padding: 18,
    width: '100%',
  },
  installPromptTitle: {
    color: '#241c18',
    fontSize: 22,
    fontWeight: '800',
  },
  installPromptText: {
    color: '#4e433d',
    fontSize: 14,
    lineHeight: 20,
  },
  installStepList: {
    gap: 10,
  },
  installStepRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  installStepNumber: {
    alignItems: 'center',
    backgroundColor: '#e8dfd7',
    borderRadius: 6,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  installStepNumberText: {
    color: '#4e433d',
    fontSize: 13,
    fontWeight: '800',
  },
  installStepContent: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    minWidth: 0,
    paddingTop: 1,
  },
  installStepText: {
    color: '#241c18',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  shareIcon: {
    height: 26,
    position: 'relative',
    width: 24,
  },
  shareIconBox: {
    borderColor: '#176cc4',
    borderRadius: 3,
    borderWidth: 2,
    bottom: 1,
    height: 16,
    left: 3,
    position: 'absolute',
    width: 18,
  },
  shareIconShaft: {
    backgroundColor: '#176cc4',
    height: 17,
    left: 11,
    position: 'absolute',
    top: 0,
    width: 2,
  },
  shareIconHead: {
    backgroundColor: '#176cc4',
    height: 10,
    position: 'absolute',
    top: 0,
    width: 2,
  },
  shareIconHeadLeft: {
    left: 8,
    transform: [{ rotate: '45deg' }],
  },
  shareIconHeadRight: {
    left: 14,
    transform: [{ rotate: '-45deg' }],
  },
  installPromptActions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
  },
  installPromptSecondaryButton: {
    alignItems: 'center',
    borderColor: '#cbbdb3',
    borderRadius: 6,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 14,
  },
  installPromptSecondaryText: {
    color: '#4e433d',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  installPromptPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#784c61',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 16,
  },
  installPromptPrimaryText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  modalBackdrop: {
    backgroundColor: 'rgba(36, 28, 24, 0.36)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#f6f3ef',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: '82%',
    padding: 18,
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalTitle: {
    color: '#241c18',
    fontSize: 22,
    fontWeight: '800',
  },
  modalCloseButton: {
    borderColor: '#cbbdb3',
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  modalCloseText: {
    color: '#4e433d',
    fontSize: 14,
    fontWeight: '800',
  },
  modalOptions: {
    gap: 8,
    paddingBottom: 18,
  },
  modalOption: {
    backgroundColor: '#ffffff',
    borderColor: '#d8ccc2',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  modalOptionActive: {
    backgroundColor: '#784c61',
    borderColor: '#784c61',
  },
  modalOptionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  modalOptionValue: {
    color: '#241c18',
    fontSize: 20,
    fontWeight: '800',
  },
  modalOptionValueActive: {
    color: '#ffffff',
  },
  modalSelectedText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  modalOptionDescription: {
    color: '#6f5d51',
    fontSize: 13,
    lineHeight: 18,
  },
  modalOptionDescriptionActive: {
    color: '#f7ede7',
  },
});

